# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{feedback}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Your Name"]
  s.date = %q{2011-07-14}
  s.email = %q{you@email.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/feedback/feedback_controller.rb",
    "app/controllers/feedback/widgets_controller.rb",
    "app/helpers/application_helper.rb",
    "app/helpers/feedback/widgets_helper.rb",
    "app/models/feedback/feedback.rb",
    "app/models/feedback/widget.rb",
    "app/views/feedback/feedbacks/new.html.erb",
    "app/views/feedback/widgets/index.html.erb",
    "app/views/feedback/widgets/show.html.erb",
    "app/views/layouts/feedback.html.erb",
    "config/routes.rb",
    "lib/acts_as_widget/base.rb",
    "lib/application_controller.rb",
    "lib/application_helper.rb",
    "lib/engine.rb",
    "lib/feedback.rb",
    "lib/rails/railties/tasks.rake",
    "public/images/cheese.jpg",
    "public/stylesheets/feedback.css"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Description of your gem}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

